### ISSUE TITLE
Error on corrupted filenames inside archives on conversion to cbz

### ISSUE THREAD

**Issue by xd1986k** [dickloraine/EmbedComicMetadata#10]
Hello.
Some of my archives have items with weird filenames which I assume is due to corruption of data like so 
ÉÑE-1033-077
âAâNâGâèâA1 0001
EmbedComicMetadata throws the following error "The filename, directory name, or volume label syntax is incorrect" upon trying to convert those archives to cbz.

**Comment by dickloraine** [comment]
I can't fix corrupted data in the source files. Not an issue of the plugin, sorry.
