### ISSUE TITLE
Error when Number tag contains non-numeric value

### ISSUE THREAD

**Issue by tletnes** [dickloraine/EmbedComicMetadata#11]
The ComicInfo.xml tag is not limited to numeric data in ComicRack. Values like "Multiple" will cause an error when they are found.

**Comment by dickloraine** [comment]
I assume you meant the volume field? If so, this is fixed now.

**Comment by tletnes** [comment]
No, the Number field (for the issue number)

-Thad

Sent from my iPhone

On Jan 17, 2019, at 4:10 AM, dickloraine <notifications@github.com<mailto:notifications@github.com>> wrote:


I assume you meant the volume field? If so, this is fixed now.

**Comment by dickloraine** [comment]
Strange that Comicrack assigns a string to a field named "Number"... Regardless, that was fixed too with the update. These fields are now just ignored, if they do not contain a number.

**Comment by tletnes** [comment]
That works for me. Thanks!
