### ISSUE TITLE
volume to series name

### ISSUE THREAD

**Issue by Nosirus** [dickloraine/EmbedComicMetadata#13]
for better organized calibre with the series and volume I have not found a good solution, apart from adding the volume to the name of the series "seriename (volume)"

is it possible to make it automatic?

**Comment by dickloraine** [comment]
I think you can do that already. You can make a custom column containing the volume and sort with that and the series name. If you prefer to have the series name and volume together in one column, you can make a custom column composed of the volume column and the series_name column (which would autmatically do what you want).

**Comment by Nosirus** [comment]
I can't figure out how to do this, can you help me?

**Comment by dickloraine** [comment]
- First go to calibres Preferences
- Click on "Add your own columns"
- Click on the big + icon
- enter "volume" as lookup name and "Volume" as column heading
- In the Column type dropdown select "Integers"
- Click ok 
- find your new column and check the mark on the left of it, to show it in the main window
- restart calibre

- Open the config for this plugin
- In the dropdown for Volume select your "volume" column.

Now you can sort with the new column. Maybe you have to reimport the metadata for the comics.

If you want a column with series_name and Volume together, follow the instructions for creating a new column in calibre and chose your own names. This time select "Column build from other columns" from the column type dropdown. Copy and paste the next line into the Template field:

{series} {#volume}

Now you have a column combining the two.
