### ISSUE TITLE
Error when converting to CBZ

### ISSUE THREAD

**Issue by lopiv2** [dickloraine/EmbedComicMetadata#14]
![errorconversion](https://user-images.githubusercontent.com/58883759/95074700-49438e00-070f-11eb-93e5-4eecdad3df09.png)

Error displayed when trying to convert CBR files to CBZ with the plugin button. 
Only after updating to calibre 5.0.1 (Python 3)

**Comment by dickloraine** [comment]
Thanks for the report.
