### ISSUE TITLE
Error during conversion to CBZ

### ISSUE THREAD

**Issue by sommella** [dickloraine/EmbedComicMetadata#22]
Hi,
could you please help?

See details of the error below:

`calibre, version 5.24.0
ERRORE: Eccezione non gestita: <b>OSError</b>:(2, "Failed to open archive at: 'C:\\\\Users\\\\Marco\\\\AppData\\\\Local\\\\Temp\\\\calibre_k56j5hyn\\\\rc4p0alj.cbr' with underlying unrar error code: ERAR_BAD_ARCHIVE", 'C:\\Users\\Marco\\AppData\\Local\\Temp\\calibre_k56j5hyn\\rc4p0alj.cbr')

calibre 5.24 Portable embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: Clean Metadata (0, 0, 6) && Embed Comic Metadata (1, 6, 1) && Kobo Utilities (2, 14, 1) && Modify ePub (1, 6, 3) && Quality Check (1, 11, 2)
Traceback (most recent call last):
  File "unrardll\__init__.py", line 144, in open_archive
unrar.UNRARError: ERAR_BAD_ARCHIVE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.EmbedComicMetadata.ui", line 98, in main_menu_triggered
  File "calibre_plugins.EmbedComicMetadata.main", line 51, in embed_into_comic
  File "calibre_plugins.EmbedComicMetadata.main", line 127, in iterate_over_books
  File "calibre_plugins.EmbedComicMetadata.main", line 162, in convert_to_cbz
  File "calibre_plugins.EmbedComicMetadata.comicmetadata", line 306, in convert_cbr_to_cbz
  File "calibre\utils\unrar.py", line 56, in extract
  File "unrardll\__init__.py", line 283, in extract
  File "contextlib.py", line 113, in __enter__
  File "unrardll\__init__.py", line 149, in open_archive
OSError: (2, "Failed to open archive at: 'C:\\\\Users\\\\Marco\\\\AppData\\\\Local\\\\Temp\\\\calibre_k56j5hyn\\\\rc4p0alj.cbr' with underlying unrar error code: ERAR_BAD_ARCHIVE", 'C:\\Users\\Marco\\AppData\\Local\\Temp\\calibre_k56j5hyn\\rc4p0alj.cbr')
`

**Comment by TigerC10** [comment]
If you take that CBR file `C:\Users\Marco\AppData\Local\Temp\calibre_k56j5hyn\rc4p0alj.cbr` and rename it to have a .rar extension (`C:\Users\Marco\AppData\Local\Temp\calibre_k56j5hyn\rc4p0alj.cbr.rar`) then can you extract it with a standard RAR tool like WinRAR?

Or, if you rename it to have a .zip extension does a standard unzip utility work on it?  If the .zip extension works then it might actually be a CBZ file and not a CBR.

Is there a password protection on the archive file?

**Comment by sommella** [comment]
Hi,
thanks for the reply.

Indeed it seems that I have many cbr files that are actually cbz with wrong extension.

Is there any way in the plugin to manage this scenario?
Like to detect that is not a rar but zip and simply rename the file extension?

Thanks

**Comment by dickloraine** [comment]
Currently there is no way in the plugin to fix this. It would be possible to fix it, but I am not shure, if I want to support that case. Wrongly named cbr would be possible to implement without much overhead in runtime, but the other way around would slow the plugin down. Currently I just use the format entry in calibre. For a real fix, I would need to now check for each file, if it really has the format calibre thinks it has.

Here is a dirty fix for you, You could just modify the plugin for this purpose. Download the plugin from here and extract the zip. Open the main.py file in an editor (notepad, notepad++ etc.). Scroll down to the end. Replace 

```
def convert_to_cbz(ia, metadata):
    if metadata.format == "cbr" or (metadata.format == "rar" and prefs['convert_archives']):
        metadata.convert_cbr_to_cbz()
        if prefs['delete_cbr']:
            ia.gui.current_db.new_api.remove_formats({metadata.book_id: {"cbr", "rar"}})
        return True
    elif metadata.format == "zip" and prefs['convert_archives']:
        metadata.convert_zip_to_cbz()
        if prefs['delete_cbr']:
            ia.gui.current_db.new_api.remove_formats({metadata.book_id: {"zip"}})
        return True
    return False
```

with 

```
def convert_to_cbz(ia, metadata):
    import os
    from calibre.utils.zipfile import  is_zipfile

    if metadata.format == "cbr" or (metadata.format == "rar" and prefs['convert_archives']):
        try:
            metadata.convert_cbr_to_cbz()
        except:
            zf = ia.gui.current_db.new_api.format(metadata.book_id, metadata.format, as_path=True)
            if is_zipfile(zf):
                new_fname = os.path.splitext(zf)[0] + ".cbz"
                os.rename(zf, new_fname)
                ia.gui.current_db.new_api.add_format(metadata.book_id, "cbz", new_fname)
                try:
                    if os.path.exists(new_fname):
                        os.remove(new_fname)
                except:
                    pass
                metadata.format = "cbz"
        if prefs['delete_cbr']:
            ia.gui.current_db.new_api.remove_formats({metadata.book_id: {"cbr", "rar"}})
        return True
    elif metadata.format == "zip" and prefs['convert_archives']:
        metadata.convert_zip_to_cbz()
        if prefs['delete_cbr']:
            ia.gui.current_db.new_api.remove_formats({metadata.book_id: {"zip"}})
        return True
    return False
```

Zip it and import it in calibre as a plugin from file. Select the suspected files and convert them to cbz. That should fix them, but I didn't test the code, so no guarantees. You maybe should disable the auto delete of converted files, so that they are not deleted, if something goes wrong.

**Comment by sommella** [comment]
Hi,

Thank you so much, this worked!

I tested it with both a cbr compressed with rar and with a cbr compressed with zip, in both cases the result is a cbz file properly compressed with zip.

Please consider to merge it.

Thanks
