### ISSUE TITLE
Please allow Story Arc Column to reference series-like data

### ISSUE THREAD

**Issue by loglow** [dickloraine/EmbedComicMetadata#5]
Hi, I've noticed that the Story Arc Column setting only seems to allow for choosing from an existing text-based column. I have story arc data stored in a series-like data column, which I'd like to be able to select, but it doesn't show up. I tried setting up a "column made from other columns" as a workaround, but that one didn't show up either. Please add the ability to select a series-like data column for the Story Arc Column setting. Thanks very much, and let me know if you have any questions!

**Comment by dickloraine** [comment]
Added :)
