### ISSUE TITLE
Add zip and rar to convertible formats

### ISSUE THREAD

**Issue by xd1986k** [dickloraine/EmbedComicMetadata#6]
Hello.
Could you add function to convert rar, cb7 and zip to cbz? In zip's case I'm guessing only renaming would be needed. Since calibre detects zip and rar files as their respective comic alternatives only when images are in the topmost directory you tend to accumulate quite a bit of a rar and zip files.
Thanks.

**Comment by dickloraine** [comment]
Converting rar and zip is now supported. Unfortunately 7zip would require running external programs, so I don't plan to support it.
